### ISSUE TITLE
quarkus-logging-logback has not been updated for ages 

### ISSUE THREAD

**Issue by MarcusBiel** [quarkiverse/quarkus-logging-logback#117]
Hi, I am using quarkus-logging-logback 0.13.0.
  
  To my knowledge, this is still the latest available version.

It requires me to add logback-core and logback-classic in verison 1.2.11 not to get errors in the project -
but these dependencies are totally outdated as well and give me warnings in my pom.

      <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.11</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.11</version>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.logging.logback</groupId>
            <artifactId>quarkus-logging-logback</artifactId>
            <version>0.13.0</version>
        </dependency>

Can you please update to the latest logback versions, @stuartwdouglas? 

Thanks!

**Comment by gsmet** [comment]
This has been fixed and a new version compatible with Quarkus 3 and using 1.4.6 has been released.
