### ISSUE TITLE
Dependency upgrade

### ISSUE THREAD

**Issue by Angel0926** [quarkiverse/quarkus-logging-logback#137]
Hi everyonе, In our project automatically changed <quarkus-logging-logback.version>0.13.0</quarkus-logging-logback.version> to <quarkus-logging-logback.version>1.0.0</quarkus-logging-logback.version> and added
<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
dependency version <slf4j.version>2.0.5</slf4j.version>, and after can't seen logs.

I fixed that with upgrading  dependency slf4j.jboss.logmanager from 1.x.x version to <slf4j.jboss.logmanager>2.0.1.Final</slf4j.jboss.logmanager>.  
 <dependency>
            <groupId>org.jboss.slf4j</groupId>
            <artifactId>slf4j-jboss-logmanager</artifactId>
            <version>${slf4j.jboss.logmanager}</version>
        </dependency>

Maybe this update was previously passed automatically?

**Comment by gsmet** [comment]
If you are still using Quarkus 2.x, you should keep Quarkus Logging Logback 0.x.

If you upgrade to Quarkus 3.x, then upgrade it to 1.0.0 and things will work out of the box.
