### ISSUE TITLE
Quarkus - quarkus-logging-logback issues with TimeBasedRollingPolicy

### ISSUE THREAD

**Issue by AnthonyChaput** [quarkiverse/quarkus-logging-logback#143]
Hello, 
as i told you in the google group : 
https://groups.google.com/g/quarkus-dev/c/dr0tPawdbhQ

I'm having an issue with a quarkus sample project using quarkus logging logback , JVM mode
when i add this kind of Policy : 
< r o l  l i n g P o l i c y class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy"> 

An error occurs : 
Cannot read field "fileNamePattern" because "this.tbrp" is null  
(tbrp means TimeBasedRollingPolicy i suppose)

I made a zip quarkus-sample-log.zip of my project (intellij with quarkus configuration) 

I explain in the README.md fil how to reproduce the issue, hope it will help ... 

[quarkus-sample-log.zip](https://github.com/quarkiverse/quarkus-logging-logback/files/12183909/quarkus-sample-log.zip)

**Comment by gsmet** [comment]
Could you test https://github.com/quarkiverse/quarkus-logging-logback/pull/144 ?

It fixes the NPE but... I was unable to get anything logged to the file I declared. Could you have a look at the config to see if I did something incorrect (I'm not familiar with Logback).
Also it would be nice if you could test it with your project.

**Comment by AnthonyChaput** [comment]
Greatttttttttttt !!!!!! 
Replacing the file LoggingLogbackProcessor.java with the #144  works very well now .
Thank you very much @gsmet 

PS: will a next release incorporate the fix ? 


_Excellent week end à vous et encore merci._

**Comment by gsmet** [comment]
@AnthonyChaput ideally, I would like to have a test. Any chance you could have a look at the test I created and check why I don't get anything logged? That would be helpful.

**Comment by gsmet** [comment]
Note that I don't expect the test to pass as I need to be more clever about finding the file, but I don't see any log file created in `target/`

**Comment by AnthonyChaput** [comment]
i fixed my network troubles . 

But now with your testfiles i have : 
![image](https://github.com/quarkiverse/quarkus-logging-logback/assets/139109278/79d3f4ae-fbaa-4d7b-8144-87f9b3de069e)

**Comment by AnthonyChaput** [comment]
Hi @gsmet , 
Here is (in attachment) a correct version of the sample project 
[quarkus-sample-log.zip](https://github.com/quarkiverse/quarkus-logging-logback/files/12232929/quarkus-sample-log.zip)

Search for the @gsmet in the files to understand some of my changes, but your testing lines work now and i try to respect as much as possible the file names...

**Comment by gsmet** [comment]
@AnthonyChaput thanks, it helped. I merged the PR and will push a new version.

Fixed in https://github.com/quarkiverse/quarkus-logging-logback/pull/144

**Comment by gsmet** [comment]
1.1.2 is available on Maven Central.
