### ISSUE TITLE
Issue while appending the log to appender [quarkus-logging-logback -0.0.3]

### ISSUE THREAD

**Issue by meetniyazi** [quarkiverse/quarkus-logging-logback#15]
Hi , 
After configuring the logback.xml file , my customize kafka appender is starting successfully , 
But while appending any log , appender calls method of LoggingEventWrapper class
public LoggerContextVO getLoggerContextVO() {
        return null;
    }

which always return null, and kafka appender get fails,  i am using the standard lib for kafka appender  , so i am not able to change in it.

Thanks for the help!!

**Comment by stuartwdouglas** [comment]
Do you have a reproducer?

**Comment by meetniyazi** [comment]
Its basically uses the following lines 
Map<String, String> propertyMap = loggingEvent.getLoggerContextVO().getPropertyMap();
        propertyMap.put("meta_component", this.component);
to set the properties , but even before that its get fail.

Is there any way to configure this . I tried to create the custom class by extending the lib kafka appender but after that getting class not found exception , but i can see the class is present in the class path

Thanks for the help !!

to set some
