### ISSUE TITLE
Logback ignores log level set in logback.xml, warning in Quarkus startup

### ISSUE THREAD

**Issue by peterhuba** [quarkiverse/quarkus-logging-logback#37]
Hello,

Seems like the log level property set by the addon to Quarkus is incorrect. I receive the following app output:
`(Quarkus Main Thread) WARN  [io.quarkus.config] Unrecognized configuration key "quarkus.log.categories.\"com.some.package\".level" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

This seems fair, since according to the Quarkus guide, property should not be `quarkus.log.categories.<category-name>.level`, but `quarkus.log.category."<category-name>".level`: https://quarkus.io/guides/logging

Also, the application doesn't seem to take into account the log levels set for certain specific classes, just takes the root level.

All the above was run in quarkus dev mode. Reproducer: https://github.com/peterhuba/quarkus-logback-issues

**Comment by gsmet** [comment]
I created https://github.com/quarkiverse/quarkus-logging-logback/pull/38 . I will release a fix shortly once CI passes.

**Comment by gsmet** [comment]
`0.10.0` fixes it. Thanks for the reproducer, it was helpful.
